name: Test

on:
  workflow_dispatch: {}
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'


jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          ./bin/prepare-github.sh

      - name: Provision
        run: |
          ./build.sh
        env:
          ANSIBLE_FORCE_COLOR: '1'
